# Site Settings
title: Jay's things
description: A place for Jay's things
url: "https://jaywala.github.io"

# Theme Plugins & Core Configuration
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: kitian616/jekyll-TeXt-theme
# Choose from: default, dark, forest, ocean, chocolate, orange
text_skin: orange
highlight_theme: tomorrow-night

# Markdown Settings for Diagrams & Code
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Enable Built-in Markdown Enhancements
extensions:
  mermaid: true
  mathjax: true
  chartjs: false

# Sass Compiler Configuration
sass:
    quiet_deps: true
    silence_deprecations:
    - import


# Front Matter Defaults
defaults:
  - scope:
      path: "_posts/software-notes"
    values:
      categories: [software-notes]
